repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-case-conflict
    - id: check-json
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: fix-byte-order-marker
    - id: detect-private-key
    - id: check-added-large-files
    - id: mixed-line-ending
      args:
        - --fix=lf

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.3 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
        - --hook-config=--add-to-existing-file=true     # Boolean. true or false
        - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
    - id: terraform_tflint
#    - id: terraform_tfsec
#    - id: terraform_checkov
#      args:
#        - --args=--quiet
#    - id: infracost_breakdown
